= GorgeousCure
// See https://hubpress.gitbooks.io/hubpress-knowledgebase/content/ for information about the parameters.
:published_at: 2019-08-30
:hp-tags: HubPress, Blog, Open_Source,
:hp-alt-title: GorgeousCure

I've been informed that it's time to pass on some thoughts, processes, Ways of Doing Things, and the like. Not for posterity, not for ego, not because there's a drastic need for this information in the wild... but because there is one person somewhere who is looking for this information and needs it desperately. Maybe that's you. Probably not. But here we are just the same.

We're not going to talk about me today. We're going to talk about What Is To Come.  What I'm sharing is not a manifesto, not a guidebook, not a set of skills enhancement exercises. What I'm sharing is more of a nudge toward a shift in paradigms. A way to orient yourself with the world now that the world has reoriented herself.

Here we are. There is you. There is me. A clean slate. Your history has been wiped. If not, wipe it and come back. My history has been wiped. We are two beings of pure energy out in the world, and we share this incredibly vast pool of knowledge between us. Face it, we know remarkable things. 

What I bring to the table will look like exercises. They will feel like exercises. But they are escalators. Where you take them is up to you, but they are things you stand on which take you to higher places, and in my worldview that is an escalator.
